name: sniffmap frontend

on:
  push:
    branches:
      - main

jobs:
  frontend-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd app/SniffMap-front
            git pull origin main
            npm run build
            sudo systemctl restart nginx

#      - name: Run React tests
#        run: npm test
#        working-directory: frontend
